version: "2.4"
services:

  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    depends_on:
      - webapp
    volumes:
      - "./nginx/sites-enabled:/etc/nginx/sites-enabled/"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"

  webapp:
    image: "ayo_ta"
    restart: "on-failure"
    environment:
      PORT: "8080"
    # ports:
    #   - "8080:8080"
    volumes:
      - "./webapp/:/app"
    